[package]
name = "sonar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sonar-db = { workspace = true }
sonar-api = { workspace = true }
sonar-ingestor = { workspace = true, optional = true }
sonar-sol-price = { workspace = true, optional = true }
sonar-scheduler = { workspace = true }
sonar-streams = { workspace = true }

tracing = { workspace = true }
tracing-otel-extra = { workspace = true, features = ["env"] }

anyhow = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
clap = { workspace = true }

[build-dependencies]
vergen = { version = "8.3.2", features = ["build", "cargo", "git", "gitcl"] }

[features]
default = ["ws"]
ws = ["sonar-ingestor", "sonar-sol-price"]
block = ["sonar-ingestor/hist", "sonar-sol-price"]
